version: '4.8.2'
services:
  web:
    build: .
    command: ./wait-for-it.sh mysql:3306 -- ./docker-entrypoint.sh
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - mysql
      - redis
      - celery
      - smtp4dev
    restart: on-failure
    container_name: classroom_api
    volumes:
      - .:/app
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306
    restart: always
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    environment:
      - MYSQL_DATABASE=classroom
      - MYSQL_ROOT_PASSWORD=Abcd_1234
    volumes:
      - mysqldata:/var/lib/mysql    
  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redisdata:/data
  smtp4dev:
    image: rnwood/smtp4dev
    container_name: email
    ports:
      - 5000:80
      - 25:25
    restart: always
  celery:
    build: .
    command: celery -A core worker -l info -P eventlet -E
    depends_on:
      - redis
    container_name: celery
    volumes:
      - .:/app
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=classroom
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 
volumes:
  mysqldata:
  redisdata:    
  pgdata:

  # celery-beat:
  #   build: .
  #   command: celery -A storefront beat --loglevel=info
  #   depends_on:
  #     - redis
  #   volumes:
  #     - .:/app
  # flower:
  #   build: .
  #   command: celery -A storefront flower
  #   depends_on:
  #     - web
  #     - redis
  #     - celery
  #   environment:
  #     - DEBUG=1
  #     - CELERY_BROKER=redis://redis:6379/0
  #     - CELERY_BACKEND=redis://redis:6379/0
  #   ports:
  #     - 5555:5555
  # tests:
  #   build: .
  #   command: ./wait-for-it.sh mysql:3306 -- ptw
  #   depends_on:
  #     - redis
  #     - mysql
  #   tty: true
  #   volumes:
  #     - .:/app
  # postgres:
  #   image: postgres
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=classroom
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres 