# Generated by Django 4.0.4 on 2022-04-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseaccount',
            name='email',
            field=models.EmailField(help_text='This will be used as username for login', max_length=250, unique=True, verbose_name='Email Id'),
        ),
    ]
