# Generated by Django 4.0.4 on 2022-05-01 16:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=255, verbose_name='College Name')),
                ('level', models.CharField(help_text='e.g - UG/PG/MASTERS', max_length=40, verbose_name='Level')),
                ('stream', models.CharField(max_length=255, verbose_name='Your Stream')),
                ('start_year', models.PositiveSmallIntegerField(db_index=True, help_text='Write your session starting year (e.g. - 2020)', validators=[django.core.validators.MinValueValidator(2000, "You can't select year less than 2000"), django.core.validators.MaxValueValidator(2022, 'Max Year Can be selected only 1 year ahead of current year')], verbose_name='Starting Year')),
                ('end_year', models.PositiveSmallIntegerField(db_index=True, help_text='Write your session ending year (e.g. - 2020)', validators=[django.core.validators.MinValueValidator(2000, "You can't select year less than 2000"), django.core.validators.MaxValueValidator(2200, 'Max Year Can be selected only 1 year ahead of current year')], verbose_name='Ending Year')),
                ('university_roll', models.PositiveBigIntegerField(db_index=True, help_text='Your University Roll No - (e.g. - 13071020030)', unique=True, verbose_name='University Roll')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='classroom.classroom')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
