# Generated by Django 4.0.4 on 2022-05-02 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.RemoveField(
            model_name='student',
            name='college',
        ),
        migrations.RemoveField(
            model_name='student',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='level',
        ),
        migrations.RemoveField(
            model_name='student',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='student',
            name='university_roll',
        ),
    ]
