# Generated by Django 4.0.4 on 2022-05-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_teacher_classroom_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='classroom',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='classroom.classroom'),
        ),
    ]
