# Generated by Django 4.0.4 on 2022-05-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_alter_teacher_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='university_roll',
            field=models.PositiveBigIntegerField(help_text='Your University Roll No - (e.g. - 13071020030)', null=True, verbose_name='University Roll'),
        ),
    ]
