# Generated by Django 4.0.4 on 2022-05-09 21:04

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0008_allowedstudents"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        populate_from=[
                            "title",
                            "semester__sem_no",
                            "subject_type",
                            "credit_points",
                            "created_by",
                        ],
                    ),
                ),
                ("subject_code", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=200)),
                (
                    "subject_type",
                    models.CharField(
                        choices=[
                            ("TH", "Theory"),
                            ("PRC", "Practical"),
                            ("ELC", "Elective"),
                            ("PRJ", "Project"),
                        ],
                        default="TH",
                        max_length=5,
                    ),
                ),
                (
                    "credit_points",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10"),
                            (11, "11"),
                            (12, "12"),
                            (13, "13"),
                            (14, "14"),
                            (15, "15"),
                        ],
                        default=1,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="classroom.teacher",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="classroom.semester",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "title", "-credit_points"],
            },
        ),
    ]
