# Generated by Django 4.0.4 on 2022-05-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_student_university_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='university_roll',
            field=models.PositiveBigIntegerField(default=5543777, help_text='Your University Roll No - (e.g. - 13071020030)', null=True, verbose_name='University Roll'),
        ),
    ]
