# Generated by Django 4.0.4 on 2022-05-07 09:38

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_alter_student_university_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='university_roll',
            field=models.PositiveBigIntegerField(default=4145274, help_text='Your University Roll No - (e.g. - 13071020030)', null=True, verbose_name='University Roll'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title', 'subject_type', 'semester__sem_no', 'credit_points'])),
                ('subject_code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('subject_type', models.CharField(choices=[('T', 'Theory'), ('P', 'Practical'), ('E', 'Elective')], default='T', max_length=5)),
                ('credit_points', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='classroom.semester')),
            ],
            options={
                'ordering': ['-created_at', 'title', '-credit_points'],
            },
        ),
    ]
