# Generated by Django 4.0.4 on 2022-05-07 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_alter_student_university_roll_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='created_by',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='classroom.teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='university_roll',
            field=models.PositiveBigIntegerField(default=9079214, help_text='Your University Roll No - (e.g. - 13071020030)', null=True, verbose_name='University Roll'),
        ),
    ]
