# Generated by Django 4.0.4 on 2022-05-07 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_subject_created_by_alter_student_university_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='university_roll',
            field=models.PositiveBigIntegerField(default=7176144, help_text='Your University Roll No - (e.g. - 13071020030)', null=True, verbose_name='University Roll'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(default='No Heading Given', verbose_name='Heading')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Description[Optional] ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Created At ')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='classroom.teacher')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='classroom.subject')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
