# Generated by Django 4.0.4 on 2022-05-08 12:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0015_alter_announcement_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title', 'subject__title', 'posted_by__user__first_name'])),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description[optional]')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At ')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notes', to='classroom.teacher')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='classroom.subject')),
            ],
            options={
                'verbose_name_plural': 'Notes',
                'ordering': ['title', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='university_roll',
            field=models.PositiveBigIntegerField(default=8592578, help_text='Your University Roll No - (e.g. - 13071020030)', null=True, verbose_name='University Roll'),
        ),
        migrations.CreateModel(
            name='NotesAttachmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='notesfile-#', max_length=60, null=True, verbose_name='Title[Optional] ')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='P:\\Codes\\SEM_4_Major_Project\\Code\\ClassroomBackend\\media/classroom/notes/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'pdf', 'doc'], message='Please Upload XLSX/PDF/Doc file only')], verbose_name='Upload File Here')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At ')),
                ('notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_files', to='classroom.notes')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
