# Generated by Django 4.0.4 on 2022-05-08 12:50

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_notes_alter_student_university_roll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesattachmentfile',
            name='title',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=['notes__title', 'notes__subject__title', 'created_at']),
        ),
        migrations.AlterField(
            model_name='student',
            name='university_roll',
            field=models.PositiveBigIntegerField(default=8829245, help_text='Your University Roll No - (e.g. - 13071020030)', null=True, verbose_name='University Roll'),
        ),
    ]
