# Generated by Django 4.0.4 on 2022-05-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0017_allowedteacherclassroomlevel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="teachers",
            field=models.ManyToManyField(
                blank=True,
                editable=False,
                related_name="classrooms",
                to="classroom.teacher",
            ),
        ),
    ]
