# Generated by Django 4.0.4 on 2022-05-12 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0019_alter_notesattachmentfile_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notesattachmentfile",
            name="file_path",
            field=models.FileField(
                blank=True,
                max_length=400,
                null=True,
                upload_to="P:\\Codes\\SEM_4_Major_Project\\Code\\ClassroomBackend\\media/classroom/notes/%Y/%m/%d",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["xlsx", "pdf", "doc"],
                        message="Please Upload XLSX/PDF/Doc file only",
                    )
                ],
                verbose_name="Upload File Here",
            ),
        ),
    ]
