# Generated by Django 4.0.4 on 2022-05-09 10:35

import classroom.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0020_alter_classroom_allowed_student_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='level',
            field=models.CharField(choices=[('Bachelors', 'Undergraduate'), ('Masters', 'Postgraduate')], default='Bachelors', help_text='e.g - Masters/Bachelors', max_length=40, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='no_of_semesters',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(4, 'Min Course Duration is of 2 Years(4 semesters)'), django.core.validators.MaxValueValidator(14), classroom.validators.is_no_of_sem_even], verbose_name='Number of Sem'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='section',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='A', max_length=10, null=True, verbose_name='Section(optional)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='university_roll',
            field=models.PositiveBigIntegerField(default=54553, help_text='Your University Roll No - (e.g. - 13071020030)', null=True, verbose_name='University Roll'),
        ),
    ]
