# Generated by Django 4.0.4 on 2022-05-09 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0022_alter_classroom_allowed_student_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='allowed_student_list',
            field=models.FileField(blank=True, null=True, upload_to='P:\\Codes\\SEM_4_Major_Project\\Code\\ClassroomBackend\\media/classroom/students/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx'], message='Please Upload CSV/XLSX file only')], verbose_name='Upload student List File(.csv)'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='allowed_teacher_list',
            field=models.FileField(blank=True, null=True, upload_to='P:\\Codes\\SEM_4_Major_Project\\Code\\ClassroomBackend\\media/classroom/teachers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx'], message='Please Upload CSV/XLSX file only')], verbose_name='Upload teacher List File(.csv)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='university_roll',
            field=models.PositiveBigIntegerField(default=7900594, help_text='Your University Roll No - (e.g. - 13071020030)', null=True, verbose_name='University Roll'),
        ),
    ]
