# Generated by Django 4.0.4 on 2022-05-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "classroom",
            "0023_alter_assignment_options_assignment_alloted_marks_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Assignment",
        ),
    ]
