# Generated by Django 4.0.4 on 2022-05-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0025_collegedba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedteacher',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email Id'),
        ),
    ]
