# Generated by Django 4.0.4 on 2022-05-15 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0026_alter_allowedteacher_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllowedCollegeDBA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="Email Id"
                    ),
                ),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowed_dbas",
                        to="classroom.college",
                    ),
                ),
            ],
        ),
    ]
