# Generated by Django 4.0.4 on 2022-05-15 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0027_allowedcollegedba"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collegedba",
            name="college",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="college_dbas",
                to="classroom.college",
            ),
        ),
    ]
