# Generated by Django 4.0.4 on 2022-05-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0030_college_allowed_dba_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="college",
            name="owner_email_id",
            field=models.EmailField(
                default=None,
                max_length=254,
                unique=True,
                verbose_name="College Owner DBA Mail [unique]",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="collegedba",
            name="is_owner",
            field=models.BooleanField(default=False, verbose_name="Owner [✔/❌]"),
        ),
    ]
