# Generated by Django 4.0.4 on 2022-05-19 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0031_college_owner_email_id_collegedba_is_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collegedba",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="college_dbas",
                to="classroom.college",
            ),
        ),
    ]
