# Generated by Django 4.0.4 on 2022-05-21 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0034_alter_classroom_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="allowed_student_list",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="classroom/students/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["csv", "xlsx"],
                        message="Please Upload CSV/XLSX file only",
                    )
                ],
                verbose_name="Upload Student List File(.csv/xl)",
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="allowed_teacher_list",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="classroom/teachers/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["csv", "xlsx"],
                        message="Please Upload CSV/XLSX file only",
                    )
                ],
                verbose_name="Upload Teacher List File(.csv/xl)",
            ),
        ),
        migrations.AlterField(
            model_name="college",
            name="allowed_dba_list",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="college/dbas/%Y/%m/%d",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["csv", "xlsx"],
                        message="Please Upload CSV/XLSX file only",
                    )
                ],
                verbose_name="Upload DBA List File(.csv/.xl)",
            ),
        ),
        migrations.AlterField(
            model_name="college",
            name="allowed_teacher_list",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="classroom/teachers/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["csv", "xlsx"],
                        message="Please Upload CSV/XLSX file only",
                    )
                ],
                verbose_name="Upload teacher List File(.csv/.xl)",
            ),
        ),
        migrations.AlterField(
            model_name="notesattachmentfile",
            name="file_path",
            field=models.FileField(
                blank=True,
                max_length=400,
                null=True,
                upload_to="classroom/notes/%Y/%m/%d",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["xlsx", "pdf", "doc"],
                        message="Please Upload XLSX/PDF/Doc file only",
                    )
                ],
                verbose_name="Upload File Here",
            ),
        ),
    ]
