# Generated by Django 4.0.4 on 2022-05-21 15:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0035_alter_classroom_allowed_student_list_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="college",
            name="stream_list",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="college/streams/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["csv", "xlsx"],
                        message="Please Upload CSV/XLSX file only",
                    )
                ],
                verbose_name="Upload Stream List File(.csv/.xl)",
            ),
        ),
        migrations.CreateModel(
            name="Stream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streams",
                        to="classroom.college",
                    ),
                ),
                (
                    "dba",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streams",
                        to="classroom.collegedba",
                    ),
                ),
            ],
        ),
    ]
