# Generated by Django 4.0.4 on 2022-05-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0036_college_stream_list_stream"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stream",
            options={"ordering": ["college__name", "title"]},
        ),
        migrations.AlterField(
            model_name="subject",
            name="credit_points",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                    (11, "11"),
                    (12, "12"),
                    (13, "13"),
                    (14, "14"),
                    (15, "15"),
                    (16, "16"),
                    (17, "17"),
                    (18, "18"),
                    (19, "19"),
                    (20, "20"),
                ],
                default=1,
            ),
        ),
    ]
