# Generated by Django 4.0.4 on 2022-05-22 13:28

import classroom.validators
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0039_alter_subject_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="Assignment Title"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "alloted_marks",
                    models.PositiveSmallIntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MaxValueValidator(
                                100,
                                "assignments can't be alloted more than 100 marks 😑",
                            )
                        ],
                        verbose_name="Marks:",
                    ),
                ),
                (
                    "attached_pdf",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to="classroom/assignments/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"],
                                message="Please Upload PDF file only",
                            ),
                            classroom.validators.pdf_file_size_lt_5mb,
                        ],
                        verbose_name="Upload File Here📁",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        default=datetime.date(2022, 5, 23),
                        validators=[classroom.validators.assignment_date_gte_today],
                        verbose_name="Due by",
                    ),
                ),
                (
                    "due_time",
                    models.TimeField(
                        default=datetime.time(13, 28, 5, 829323),
                        verbose_name="Due time",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At "),
                ),
                (
                    "given_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments_given",
                        to="classroom.teacher",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="classroom.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "due_time", "alloted_marks", "-created_at"],
            },
        ),
    ]
