# Generated by Django 4.0.4 on 2022-05-22 13:39

import classroom.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0041_alter_assignment_due_time_submittedassignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="due_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                validators=[classroom.validators.assignment_date_gte_today],
                verbose_name="Due by",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="due_time",
            field=models.TimeField(
                default=django.utils.timezone.now, verbose_name="Due time"
            ),
        ),
    ]
