# Generated by Django 4.0.4 on 2022-05-22 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0043_rename_submittedassignment_assignmentsubmission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="given_by",
        ),
        migrations.RemoveField(
            model_name="assignmentsubmission",
            name="scored_by",
        ),
    ]
