# Generated by Django 4.0.4 on 2022-05-23 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0044_remove_assignment_given_by_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="college",
            options={"ordering": ["name", "city"]},
        ),
    ]
