# Generated by Django 4.0.4 on 2022-05-23 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0045_alter_college_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subject",
            options={"ordering": ["subject_code", "title", "-subject_type"]},
        ),
    ]
