# Generated by Django 4.0.4 on 2022-05-28 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0046_alter_subject_options"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stream",
            unique_together={("title", "dba")},
        ),
    ]
