# Generated by Django 4.0.4 on 2022-05-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0047_alter_stream_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="allowedstudents",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="allowedstudents",
            name="email",
            field=models.EmailField(
                max_length=255, unique=True, verbose_name="Email Id"
            ),
        ),
    ]
