# Generated by Django 4.0.4 on 2022-06-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0048_alter_allowedstudents_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="section",
            field=models.CharField(
                blank=True,
                default="A",
                max_length=5,
                null=True,
                verbose_name="Section(optional)",
            ),
        ),
    ]
